name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt 

    - name: Run tests
      run: pytest

    - name: Measure code coverage
      run: pytest --cov=.

    - name: Generate documentation
      run: python pydoc -w

    #- name: Deploy to production
    #  if: github.ref == 'refs/heads/main'
     # run: |
     #   pip install -r requirements-deploy.txt
      #  fab deploy
